//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YuewenNote.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YuewenNote.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to export.
        /// </summary>
        internal static string ErrorMsgFailedToExport {
            get {
                return ResourceManager.GetString("ErrorMsgFailedToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + G.
        /// </summary>
        internal static string MenuGestureFileNewGroup {
            get {
                return ResourceManager.GetString("MenuGestureFileNewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + N.
        /// </summary>
        internal static string MenuGestureFileNewSheet {
            get {
                return ResourceManager.GetString("MenuGestureFileNewSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string MenuHeaderFile {
            get {
                return ResourceManager.GetString("MenuHeaderFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Group.
        /// </summary>
        internal static string MenuHeaderFileNewGroup {
            get {
                return ResourceManager.GetString("MenuHeaderFileNewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Sheet.
        /// </summary>
        internal static string MenuHeaderFileNewSheet {
            get {
                return ResourceManager.GetString("MenuHeaderFileNewSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M1.9999994,5.0000134L1.9999994,22.355972C4.999999,21.919082 9.4349957,21.656021 16.008999,25.487076 22.106012,22.062027 27.999994,22.199966 29.999992,22.485L29.999992,5.0000134 27.345419,5.0000134 27.335798,18.616976C27.335798,18.778976 27.335798,19.270975 26.909805,19.607975 26.645809,19.816974 26.296816,19.890974 25.951822,19.809974 25.46883,19.694975 25.080837,19.645975 24.651844,19.645975 22.187887,19.645975 18.381954,21.236973 17.452971,23.093971 17.306973,23.385969 16.988979,23.62097 16.666985,23.6689 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TreeItemAllGryphGeometry {
            get {
                return ResourceManager.GetString("TreeItemAllGryphGeometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string TreeItemAllNameString {
            get {
                return ResourceManager.GetString("TreeItemAllNameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M2.0199045,8.4282792L2.0199045,29.041915C2.0199049,29.569931,2.4759603,29.999923,3.0368736,29.999923L21.545931,29.999923C21.747959,29.999923,21.911899,29.853927,21.911899,29.674911L21.911899,9.2289963 4.6139901,9.2289963C3.6599922,9.2289963,2.7726505,8.9379025,2.0361285,8.4398263z M4.6139901,2.0369992C3.1929932,2.0369992 2.0369959,3.1929986 2.0369959,4.6139978 2.0369959,6.0359974 3.1929932,7.1919971 4.6139901,7.1919971L15.713911,7.1919971 15.713911,5.6329601 4.6019208,5.6329601C4.0389173,5.6329603 3.5829146 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TreeItemGroupGryphGeometry {
            get {
                return ResourceManager.GetString("TreeItemGroupGryphGeometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M15.399963,6.7999947L16.599976,6.7999947 16.599976,14.400008 16.700012,14.400008C17,14.60002,17.299988,14.900008,17.399963,15.199997L17.399963,15.300033 23,15.300033 23,16.600023 17.5,16.600023 17.5,16.699999C17.200012,17.199999 16.700012,17.600023 16,17.600023 15.099976,17.600023 14.299988,16.800035 14.299988,15.900009 14.299988,15.199997 14.700012,14.60002 15.299988,14.300032L15.399963,14.300032z M16,2.0000024C8.2999878,2.0000022 2,8.3000267 2,15.999985 2,23.700004 8.2999878,29.999998 16,29.999998 23.7000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TreeItemLast7DaysGryphGeometry {
            get {
                return ResourceManager.GetString("TreeItemLast7DaysGryphGeometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 7 Days.
        /// </summary>
        internal static string TreeItemLast7DaysNameString {
            get {
                return ResourceManager.GetString("TreeItemLast7DaysNameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M16,8.0000272L18,8.0000272 18,27.000028 16,27.000028z M11,8.0000272L13,8.0000272 13,27.000028 11,27.000028z M6.0000005,8.0000272L8.0000005,8.0000272 8.0000005,27.000028 6.0000005,27.000028z M2.9990063,5.0000274L2.9990063,30.000026 20.999983,30.000026 20.999006,5.0000274z M13.771989,1.9959999L10.198989,2.0000001C10.158989,2.025,9.9989892,2.241,9.9989892,2.6000001L9.9989892,3.0000258 13.998989,3.0000258 13.998989,2.6000001C13.998989,2.241,13.838988,2.025,13.771989,1.9959999z M10.198989,0L13.798988,0C15.031989 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TreeItemTrashGryphGeometry {
            get {
                return ResourceManager.GetString("TreeItemTrashGryphGeometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trash.
        /// </summary>
        internal static string TreeItemTrashNameString {
            get {
                return ResourceManager.GetString("TreeItemTrashNameString", resourceCulture);
            }
        }
    }
}
